### ISSUE TITLE
Add support for pigment's markerType

### ISSUE THREAD

**Issue by dkniffin** [DeMoorJasper/vscode-pigments#3]
In the original pigments, there's a `markerType` setting that lets you choose different styles for rendering the color. The main one I'm interested in is `gutter`, but I'd also be fine with `dot` or `square-dot`

**Comment by DeMoorJasper** [comment]
Square: already exists in vscode natively
gutter & Circle: is pretty much the same as square
outline & underline: I'll add these soonish

btw If you're up for it I'm always accepting contributions, as this was a side-project which I don't heavily maintain, because it does what I want it to do for the most part.

**Comment by dkniffin** [comment]
👍 Yep, I noticed after posting this yesterday that VSCode did the squares natively. I think it just wasn't working for me in sass for some reason. No rush on getting any of these others implemented. I _might_ contribute a PR for it, but I'm not sure if I have much time either.

**Comment by GrosBourrin** [comment]
@DeMoorJasper @dkniffin 
Natively ? how ? i have 1.29.1 and nothing like that

**Comment by DeMoorJasper** [comment]
Added in 2.0
