### ISSUE TITLE
highlighting js files

### ISSUE THREAD

**Issue by mileung** [DeMoorJasper/vscode-pigments#7]
Is this possible?

**Comment by DeMoorJasper** [comment]
Unfortunately due to many issues with this plugin highlighting non colorcode hex values, this has been removed.

I would love to add it back as I personally use a lot of colors inside js and config files. Either I add it as a config flag or we need to figure out a regex that wouldn’t trigger on non color codes which is pretty hard tbh

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DeMoorJasper** [comment]
Started working on this config: f081429680a3a2d2d57275c2152e161e523e19ac will come out in v2
